In [1]:
import pandas as pd
import pyspark.sql.functions as F
from pyspark.sql.types import *
from pyspark.sql import Window
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("My PySpark App") \
    .getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/02/02 03:40:38 WARN Utils: Your hostname, tatiane-Inspiron-3583, resolves to a loopback address: 127.0.1.1; using 192.168.0.14 instead (on interface wlo1)
26/02/02 03:40:38 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/02/02 03:40:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
df = spark.read.csv("/home/tatiane/repositorios/data-projects/03_machine_learning/etl_churn_banco/raw/data/BankChurners.csv", 
                     header=True, inferSchema=True)
df.count()

10127

In [4]:
df = df.drop('Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1', 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2')

In [5]:
df.printSchema()

root
 |-- CLIENTNUM: integer (nullable = true)
 |-- Attrition_Flag: string (nullable = true)
 |-- Customer_Age: integer (nullable = true)
 |-- Gender: string (nullable = true)
 |-- Dependent_count: integer (nullable = true)
 |-- Education_Level: string (nullable = true)
 |-- Marital_Status: string (nullable = true)
 |-- Income_Category: string (nullable = true)
 |-- Card_Category: string (nullable = true)
 |-- Months_on_book: integer (nullable = true)
 |-- Total_Relationship_Count: integer (nullable = true)
 |-- Months_Inactive_12_mon: integer (nullable = true)
 |-- Contacts_Count_12_mon: integer (nullable = true)
 |-- Credit_Limit: double (nullable = true)
 |-- Total_Revolving_Bal: integer (nullable = true)
 |-- Avg_Open_To_Buy: double (nullable = true)
 |-- Total_Amt_Chng_Q4_Q1: double (nullable = true)
 |-- Total_Trans_Amt: integer (nullable = true)
 |-- Total_Trans_Ct: integer (nullable = true)
 |-- Total_Ct_Chng_Q4_Q1: double (nullable = true)
 |-- Avg_Utilization_Ratio: double (nullable = true)

In [6]:
# Analisando conteúdo completo
for coluna in df.columns:
  df.groupBy(coluna).count().show(truncate=False)

+---------+-----+
|CLIENTNUM|count|
+---------+-----+
|778493808|1    |
|716657058|1    |
|714576183|1    |
|753606108|1    |
|717392358|1    |
|721059033|1    |
|712490283|1    |
|788701608|1    |
|790082508|1    |
|710364258|1    |
|715055433|1    |
|764776833|1    |
|712500933|1    |
|709042908|1    |
|794551383|1    |
|721243083|1    |
|715277583|1    |
|713718558|1    |
|718000383|1    |
|719651358|1    |
+---------+-----+
only showing top 20 rows
+-----------------+-----+
|Attrition_Flag   |count|
+-----------------+-----+
|Existing Customer|8500 |
|Attrited Customer|1627 |
+-----------------+-----+

+------------+-----+
|Customer_Age|count|
+------------+-----+
|31          |91   |
|65          |101  |
|53          |387  |
|34          |146  |
|28          |29   |
|26          |78   |
|27          |32   |
|44          |500  |
|47          |479  |
|52          |376  |
|40          |361  |
|57          |223  |
|54          |307  |
|48          |472  |
|64          |43   |
|41          |379  |
|43          |473  |
|37          |260  |
|61          |93   |
|35          |184  |
+------------+-----+
only showing top 20 rows
+------+-----+
|Gender|count|
+------+-----+
|F     |5358 |
|M     |4769 |
+------+-----+

+---------------+-----+
|Dependent_count|count|
+---------------+-----+
|1              |1838 |
|3              |2732 |
|5              |424  |
|4              |1574 |
|2              |2655 |
|0              |904  |
+---------------+-----+

+---------------+-----+
|Education_Level|count|
+---------------+-----+
|High School    |2013 |
|Unknown        |1519 |
|Uneducated     |1487 |
|Post-Graduate  |516  |
|Doctorate      |451  |
|Graduate       |3128 |
|College        |1013 |
+---------------+-----+

+--------------+-----+
|Marital_Status|count|
+--------------+-----+
|Unknown       |749  |
|Married       |4687 |
|Divorced      |748  |
|Single        |3943 |
+--------------+-----+

+---------------+-----+
|Income_Category|count|
+---------------+-----+
|$120K +        |727  |
|$60K - $80K    |1402 |
|$80K - $120K   |1535 |
|Unknown        |1112 |
|$40K - $60K    |1790 |
|Less than $40K |3561 |
+---------------+-----+

+-------------+-----+
|Card_Category|count|
+-------------+-----+
|Platinum     |20   |
|Silver       |555  |
|Blue         |9436 |
|Gold         |116  |
+-------------+-----+

+--------------+-----+
|Months_on_book|count|
+--------------+-----+
|31            |318  |
|53            |78   |
|34            |353  |
|28            |275  |
|27            |206  |
|26            |186  |
|44            |230  |
|22            |105  |
|47            |171  |
|52            |62   |
|13            |70   |
|16            |29   |
|40            |333  |
|20            |74   |
|54            |53   |
|48            |162  |
|19            |63   |
|41            |297  |
|43            |273  |
|15            |34   |
+--------------+-----+
only showing top 20 rows
+------------------------+-----+
|Total_Relationship_Count|count|
+------------------------+-----+
|1                       |910  |
|6                       |1866 |
|3                       |2305 |
|5                       |1891 |
|4                       |1912 |
|2                       |1243 |
+------------------------+-----+

+----------------------+-----+
|Months_Inactive_12_mon|count|
+----------------------+-----+
|1                     |2233 |
|6                     |124  |
|3                     |3846 |
|5                     |178  |
|4                     |435  |
|2                     |3282 |
|0                     |29   |
+----------------------+-----+

+---------------------+-----+
|Contacts_Count_12_mon|count|
+---------------------+-----+
|1                    |1499 |
|6                    |54   |
|3                    |3380 |
|5                    |176  |
|4                    |1392 |
|2                    |3227 |
|0                    |399  |
+---------------------+-----+

+------------+-----+
|Credit_Limit|count|
+------------+-----+
|3980.0      |1    |
|4066.0      |2    |
|4800.0      |1    |
|17884.0     |1    |
|7554.0      |1    |
|5858.0      |2    |
|5776.0      |1    |
|7115.0      |1    |
|32210.0     |1    |
|7487.0      |1    |
|2734.0      |3    |
|20974.0     |2    |
|3901.0      |1    |
|5983.0      |1    |
|1761.0      |1    |
|4142.0      |3    |
|2815.0      |1    |
|10024.0     |1    |
|24533.0     |1    |
|17072.0     |1    |
+------------+-----+
only showing top 20 rows
+-------------------+-----+
|Total_Revolving_Bal|count|
+-------------------+-----+
|1580               |8    |
|1591               |6    |
|1829               |8    |
|1645               |2    |
|1342               |5    |
|1959               |3    |
|1088               |4    |
|1238               |2    |
|471                |1    |
|2142               |2    |
|2122               |2    |
|833                |1    |
|2366               |1    |
|496                |1    |
|463                |1    |
|1721               |7    |
|1025               |4    |
|1483               |5    |
|2235               |3    |
|1084               |9    |
+-------------------+-----+
only showing top 20 rows
+---------------+-----+
|Avg_Open_To_Buy|count|
+---------------+-----+
|596.0          |1    |
|692.0          |4    |
|5983.0         |1    |
|3980.0         |1    |
|12275.0        |1    |
|558.0          |4    |
|5858.0         |1    |
|10924.0        |1    |
|299.0          |2    |
|4800.0         |1    |
|14094.0        |1    |
|769.0          |4    |
|20974.0        |1    |
|11772.0        |1    |
|305.0          |2    |
|496.0          |1    |
|2815.0         |1    |
|1761.0         |1    |
|934.0          |1    |
|2862.0         |1    |
+---------------+-----+
only showing top 20 rows
+--------------------+-----+
|Total_Amt_Chng_Q4_Q1|count|
+--------------------+-----+
|1.097               |1    |
|0.526               |5    |
|0.66                |25   |
|0.204               |1    |
|1.642               |2    |
|0.772               |18   |
|0.445               |11   |
|0.262               |2    |
|1.246               |1    |
|1.393               |1    |
|1.826               |1    |
|0.84                |28   |
|0.645               |21   |
|0.481               |6    |
|0.744               |32   |
|0.907               |14   |
|0.716               |25   |
|1.017               |3    |
|0.319               |2    |
|1.242               |4    |
+--------------------+-----+
only showing top 20 rows
+---------------+-----+
|Total_Trans_Amt|count|
+---------------+-----+
|1088           |3    |
|1342           |2    |
|1238           |4    |
|1645           |3    |
|1580           |2    |
|1591           |5    |
|2366           |2    |
|2866           |3    |
|1959           |4    |
|2659           |4    |
|2142           |2    |
|4101           |4    |
|3997           |1    |
|2122           |2    |
|3749           |4    |
|3918           |4    |
|1829           |2    |
|4900           |3    |
|4519           |5    |
|5156           |1    |
+---------------+-----+
only showing top 20 rows
+--------------+-----+
|Total_Trans_Ct|count|
+--------------+-----+
|31            |100  |
|85            |148  |
|65            |166  |
|53            |85   |
|78            |190  |
|108           |21   |
|34            |107  |
|101           |25   |
|126           |10   |
|115           |25   |
|81            |208  |
|28            |73   |
|76            |198  |
|26            |56   |
|27            |82   |
|44            |127  |
|103           |31   |
|12            |4    |
|91            |62   |
|22            |35   |
+--------------+-----+
only showing top 20 rows
+-------------------+-----+
|Total_Ct_Chng_Q4_Q1|count|
+-------------------+-----+
|0.526              |10   |
|1.462              |1    |
|1.882              |1    |
|0.194              |3    |
|0.66               |43   |
|1.097              |2    |
|0.262              |1    |
|0.772              |1    |
|0.481              |24   |
|0.744              |31   |
|0.84               |9    |
|2.4                |2    |
|0.645              |11   |
|0.907              |13   |
|0.716              |2    |
|0.679              |24   |
|1.059              |8    |
|0.773              |21   |
|0.886              |19   |
|0.823              |4    |
+-------------------+-----+
only showing top 20 rows
+---------------------+-----+
|Avg_Utilization_Ratio|count|
+---------------------+-----+
|0.194                |11   |
|0.134                |14   |
|0.204                |6    |
|0.526                |7    |
|0.66                 |3    |
|0.262                |17   |
|0.445                |7    |
|0.772                |7    |
|0.716                |8    |
|0.319                |8    |
|0.07                 |26   |
|0.645                |14   |
|0.744                |4    |
|0.481                |6    |
|0.84                 |1    |
|0.907                |2    |
|0.035                |16   |
|0.679                |12   |
|0.032                |13   |
|0.693                |6    |
+---------------------+-----+
only showing top 20 rows

In [7]:
def completudeVar(df, df_nome="DataFrame"):
    """
    Gera um resumo por coluna mostrando:
    - Qtd de duplicados
    - Qtd de nulos
    - Qtd de valores únicos
    """
    colunas = df.columns
    resumo = []

    for col in colunas:
        total = df.count()
        nulos = df.filter(F.col(col).isNull()).count()
        duplicados = total - df.select(col).distinct().count()
        unicos = df.select(col).distinct().count()

        resumo.append({
            "coluna": col,
            "total": total,
            "duplicados": duplicados,
            "nulos": nulos,
            "valores_unicos": unicos
        })

    resumo_pd = pd.DataFrame(resumo)
    resumo_pd = resumo_pd.sort_values("duplicados", ascending=False).reset_index(drop=True)
    
    print(f"Resumo do {df_nome}:")
    display(resumo_pd)
    return resumo_pd

In [8]:
# Analisando qualidade do dado
completudeVar(df)

Resumo do DataFrame:

                      coluna  total  duplicados  nulos  valores_unicos
0             Attrition_Flag  10127       10125      0               2
1                     Gender  10127       10125      0               2
2             Marital_Status  10127       10123      0               4
3              Card_Category  10127       10123      0               4
4            Dependent_count  10127       10121      0               6
5            Income_Category  10127       10121      0               6
6   Total_Relationship_Count  10127       10121      0               6
7            Education_Level  10127       10120      0               7
8     Months_Inactive_12_mon  10127       10120      0               7
9      Contacts_Count_12_mon  10127       10120      0               7
10            Months_on_book  10127       10083      0              44
11              Customer_Age  10127       10082      0              45
12            Total_Trans_Ct  10127       10001      0             126
13       Total_Ct_Chng_Q4_Q1  10127        9297      0             830
14     Avg_Utilization_Ratio  10127        9163      0             964
15      Total_Amt_Chng_Q4_Q1  10127        8969      0            1158
16       Total_Revolving_Bal  10127        8153      0            1974
17           Total_Trans_Amt  10127        5094      0            5033
18              Credit_Limit  10127        3922      0            6205
19           Avg_Open_To_Buy  10127        3314      0            6813
20                 CLIENTNUM  10127           0      0           10127

                      coluna  total  duplicados  nulos  valores_unicos
0             Attrition_Flag  10127       10125      0               2
1                     Gender  10127       10125      0               2
2             Marital_Status  10127       10123      0               4
3              Card_Category  10127       10123      0               4
4            Dependent_count  10127       10121      0               6
5            Income_Category  10127       10121      0               6
6   Total_Relationship_Count  10127       10121      0               6
7            Education_Level  10127       10120      0               7
8     Months_Inactive_12_mon  10127       10120      0               7
9      Contacts_Count_12_mon  10127       10120      0               7
10            Months_on_book  10127       10083      0              44
11              Customer_Age  10127       10082      0              45
12            Total_Trans_Ct  10127       10001      0             126
13       Total_Ct_Chng_Q4_Q1  10127        9297      0             830
14     Avg_Utilization_Ratio  10127        9163      0             964
15      Total_Amt_Chng_Q4_Q1  10127        8969      0            1158
16       Total_Revolving_Bal  10127        8153      0            1974
17           Total_Trans_Amt  10127        5094      0            5033
18              Credit_Limit  10127        3922      0            6205
19           Avg_Open_To_Buy  10127        3314      0            6813
20                 CLIENTNUM  10127           0      0           10127

### Padronização dos dados para treinamento do modelo
- Transformar todas em minúsculas
- Transforma-las em categoricas

In [ ]:
# Spark usado para leitura e preparação inicial
# Conversão para pandas devido às limitações do Spark ML no ambiente local

In [9]:
df_padronizado = df.withColumn('attrition_flag', F.when(F.col('attrition_flag') == 'Existing Customer', 0).otherwise(1))
df_padronizado = df_padronizado.withColumn('Gender', F.when(F.col('Gender') == 'Female', 1).otherwise(2))

In [10]:
df_ml = df_padronizado.toPandas()

In [11]:
change_cols = ['Education_Level', 'Income_Category', 'Card_Category', 'Marital_Status']
one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', one_hot_encoder, change_cols)
    ],
    remainder='passthrough' # Mantém as outras colunas (numéricas) intactas
)

df_encoded_array = preprocessor.fit_transform(df_ml)

nomes_novas_colunas = preprocessor.get_feature_names_out()
df_encoded_ct = pd.DataFrame(df_encoded_array, columns=nomes_novas_colunas)

print(df_encoded_ct)

       cat__Education_Level_College  cat__Education_Level_Doctorate  \
0                               0.0                             0.0
1                               0.0                             0.0
2                               0.0                             0.0
3                               0.0                             0.0
4                               0.0                             0.0
...                             ...                             ...
10122                           0.0                             0.0
10123                           0.0                             0.0
10124                           0.0                             0.0
10125                           0.0                             0.0
10126                           0.0                             0.0

       cat__Education_Level_Graduate  cat__Education_Level_High School  \
0                                0.0                               1.0
1                                1.0                               0.0
2                                1.0                               0.0
3                                0.0                               1.0
4                                0.0                               0.0
...                              ...                               ...
10122                            1.0                               0.0
10123                            0.0                               0.0
10124                            0.0                               1.0
10125                            1.0                               0.0
10126                            1.0                               0.0

       cat__Education_Level_Post-Graduate  cat__Education_Level_Uneducated  \
0                                     0.0                              0.0
1                                     0.0                              0.0
2                                     0.0                              0.0
3                                     0.0                              0.0
4                                     0.0                              1.0
...                                   ...                              ...
10122                                 0.0                              0.0
10123                                 0.0                              0.0
10124                                 0.0                              0.0
10125                                 0.0                              0.0
10126                                 0.0                              0.0

       cat__Education_Level_Unknown  cat__Income_Category_$120K +  \
0                               0.0                           0.0
1                               0.0                           0.0
2                               0.0                           0.0
3                               0.0                           0.0
4                               0.0                           0.0
...                             ...                           ...
10122                           0.0                           0.0
10123                           1.0                           0.0
10124                           0.0                           0.0
10125                           0.0                           0.0
10126                           0.0                           0.0

       cat__Income_Category_$40K - $60K  cat__Income_Category_$60K - $80K  \
0                                   0.0                               1.0
1                                   0.0                               0.0
2                                   0.0                               0.0
3                                   0.0                               0.0
4                                   0.0                               1.0
...                                 ...                               ...
10122                               1.0                               0.0
10123                               1.0                               0.0
10124                               0.0                               0.0
10125                               1.0                               0.0
10126                               0.0                               0.0

       ...  remainder__Months_Inactive_12_mon  \
0      ...                                1.0
1      ...                                1.0
2      ...                                1.0
3      ...                                4.0
4      ...                                1.0
...    ...                                ...
10122  ...                                2.0
10123  ...                                2.0
10124  ...                                3.0
10125  ...                                3.0
10126  ...                                2.0

       remainder__Contacts_Count_12_mon  remainder__Credit_Limit  \
0                                   3.0                  12691.0
1                                   2.0                   8256.0
2                                   0.0                   3418.0
3                                   1.0                   3313.0
4                                   0.0                   4716.0
...                                 ...                      ...
10122                               3.0                   4003.0
10123                               3.0                   4277.0
10124                               4.0                   5409.0
10125                               3.0                   5281.0
10126                               4.0                  10388.0

       remainder__Total_Revolving_Bal  remainder__Avg_Open_To_Buy  \
0                               777.0                     11914.0
1                               864.0                      7392.0
2                                 0.0                      3418.0
3                              2517.0                       796.0
4                                 0.0                      4716.0
...                               ...                         ...
10122                          1851.0                      2152.0
10123                          2186.0                      2091.0
10124                             0.0                      5409.0
10125                             0.0                      5281.0
10126                          1961.0                      8427.0

       remainder__Total_Amt_Chng_Q4_Q1  remainder__Total_Trans_Amt  \
0                                1.335                      1144.0
1                                1.541                      1291.0
2                                2.594                      1887.0
3                                1.405                      1171.0
4                                2.175                       816.0
...                                ...                         ...
10122                            0.703                     15476.0
10123                            0.804                      8764.0
10124                            0.819                     10291.0
10125                            0.535                      8395.0
10126                            0.703                     10294.0

       remainder__Total_Trans_Ct  remainder__Total_Ct_Chng_Q4_Q1  \
0                           42.0                           1.625
1                           33.0                           3.714
2                           20.0                           2.333
3                           20.0                           2.333
4                           28.0                           2.500
...                          ...                             ...
10122                      117.0                           0.857
10123                       69.0                           0.683
10124                       60.0                           0.818
10125                       62.0                           0.722
10126                       61.0                           0.649

       remainder__Avg_Utilization_Ratio
0                                 0.061
1                                 0.105
2                                 0.000
3                                 0.760
4                                 0.000
...                                 ...
10122                             0.462
10123                             0.511
10124                             0.000
10125                             0.000
10126                             0.189

[10127 rows x 38 columns]

In [12]:
### Validação
df_encoded_ct.filter(like="Education_Level").sum()

cat__Education_Level_College          1013.0
cat__Education_Level_Doctorate         451.0
cat__Education_Level_Graduate         3128.0
cat__Education_Level_High School      2013.0
cat__Education_Level_Post-Graduate     516.0
cat__Education_Level_Uneducated       1487.0
cat__Education_Level_Unknown          1519.0
dtype: float64

Logistic Regression

In [13]:
(df_encoded_ct.filter(like="Education_Level").sum(axis=1) == 1).all()

np.True_

In [15]:
# colunas
cat_cols = [
    "Education_Level",
    "Marital_Status",
    "Income_Category",
    "Card_Category"
]

num_cols = [c for c in df_ml.columns if c not in cat_cols + ["attrition_flag"]]

In [16]:
target = 'attrition_flag'
num_cols.remove(target)

In [17]:
print("Categóricas:", cat_cols)
print("Numéricas:", num_cols)
print("Target:", target)

Categóricas: ['Education_Level', 'Income_Category', 'Card_Category', 'Marital_Status']
Numéricas: ['Avg_Open_To_Buy', 'Avg_Utilization_Ratio', 'CLIENTNUM', 'Contacts_Count_12_mon', 'Credit_Limit', 'Customer_Age', 'Dependent_count', 'Gender', 'Months_Inactive_12_mon', 'Months_on_book', 'Total_Amt_Chng_Q4_Q1', 'Total_Ct_Chng_Q4_Q1', 'Total_Relationship_Count', 'Total_Revolving_Bal', 'Total_Trans_Amt', 'Total_Trans_Ct']
Target: attrition_flag

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
        ('num', StandardScaler(), num_cols)
    ]
)

In [19]:
num_cols = [col for col in df_ml.columns if col not in cat_cols + ["attrition_flag"]]

### Sepranado X e Y

In [20]:
X = df_ml.drop(columns=["attrition_flag"])
y = df_ml["attrition_flag"]

### Train / Test Split (com estratificação)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### Processador

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ],
    remainder="passthrough"
)

### Treinar modelo (Logistic Regression)

In [14]:
pipeline = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Education_Level',
                                                   'Marital_Status',
                                                   'Income_Category',
                                                   'Card_Category'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

### Predições

In [16]:
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

### Avaliação do modelo

In [17]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nROC AUC:")
print(roc_auc_score(y_test, y_proba))

Confusion Matrix:
[[1164  537]
 [ 120  205]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.68      0.78      1701
           1       0.28      0.63      0.38       325

    accuracy                           0.68      2026
   macro avg       0.59      0.66      0.58      2026
weighted avg       0.81      0.68      0.72      2026


ROC AUC:
0.7148084836973725

## Conclusões

- O modelo apresentou bom desempenho para identificação de churn
- Variáveis comportamentais tiveram maior impacto que dados demográficos
- A abordagem com pipeline evitou data leakage
- O projeto pode ser facilmente migrado para Spark ML em ambiente Databricks completo